language: generic

services:
  - docker

before_script:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - ./build-containers.sh

after_success:
  - ./push-containers.sh
